// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acjdrqktwmytboxdyejh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjamRycWt0d215dGJveGR5ZWpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMzI0OTUsImV4cCI6MjA3MjcwODQ5NX0.xCA3-rFq9YDce5HwI5GEvmZ6rcYAaOITqcSbmuONTkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});